"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@supabase/supabase-js";
const db=createClient("https://pixlqytdhgxcfgagwijy.supabase.co","sb_publishable_twXglFUicR3kgQ3fTO3pJA_Ji3qwIwm");
const choices=["Kids","Food & Treats","Activities","Places","Birthday","Free Stuff","Veteran","Deals"];
export default function Account(){
 const[email,setEmail]=useState(""),[user,setUser]=useState<any>(null),[sent,setSent]=useState(false),[radius,setRadius]=useState(25),[interests,setInterests]=useState<string[]>([]),[alerts,setAlerts]=useState(true),[status,setStatus]=useState("");
 useEffect(()=>{db.auth.getUser().then(({data})=>{setUser(data.user||null);if(data.user)load(data.user.id)});const{data:s}=db.auth.onAuthStateChange((_e,session)=>{setUser(session?.user||null);if(session?.user)load(session.user.id)});return()=>s.subscription.unsubscribe()},[]);
 async function load(uid:string){const[{data:p},{data:a}]=await Promise.all([db.from("user_preferences").select("*").eq("user_id",uid).maybeSingle(),db.from("alert_subscriptions").select("*").eq("user_id",uid).order("created_at",{ascending:false}).limit(1).maybeSingle()]);if(p){setRadius(p.radius_miles||25);setInterests(p.interests||[])}if(a)setAlerts(a.enabled!==false)}
 async function login(){if(!email)return;setStatus("Sending sign-in link…");const{error}=await db.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin+"/account"}});setSent(!error);setStatus(error?error.message:"Check your email for the sign-in link.")}
 function toggle(x:string){setInterests(v=>v.includes(x)?v.filter(y=>y!==x):[...v,x])}
 async function save(){if(!user)return;setStatus("Saving…");await db.from("user_preferences").upsert({user_id:user.id,radius_miles:radius,interests,updated_at:new Date().toISOString()});const{data:a}=await db.from("alert_subscriptions").select("id").eq("user_id",user.id).limit(1).maybeSingle();if(a?.id)await db.from("alert_subscriptions").update({radius_miles:radius,categories:interests,enabled:alerts,updated_at:new Date().toISOString()}).eq("id",a.id);else await db.from("alert_subscriptions").insert({user_id:user.id,radius_miles:radius,categories:interests,enabled:alerts});setStatus("Saved.")}
 const label=useMemo(()=>user?.email||"",[user]);
 return <main className="accountPage"><a href="/">← Free Near Me</a><section className="accountCard"><h1>Your Free Near Me</h1>{!user?<><p>Sign in with a magic link to sync saves, interests and alert settings across devices.</p><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@email.com" type="email"/><button onClick={login}>Email me a sign-in link</button>{sent&&<b>Link sent.</b>}</>:<><p className="accountEmail">{label}</p><label>Default radius<select value={radius} onChange={e=>setRadius(Number(e.target.value))}>{[5,10,25,50].map(x=><option key={x} value={x}>{x} miles</option>)}</select></label><h2>What do you want more of?</h2><div className="interestGrid">{choices.map(x=><button key={x} className={interests.includes(x)?"active":""} onClick={()=>toggle(x)}>{x}</button>)}</div><label className="alertToggle"><input type="checkbox" checked={alerts} onChange={e=>setAlerts(e.target.checked)}/> Save my alert preferences for new nearby matches</label><button onClick={save}>Save preferences</button><button className="secondary" onClick={()=>db.auth.signOut()}>Sign out</button></>}{status&&<p className="accountStatus">{status}</p>}</section></main>
}